openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /register:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
components:
  schemas:
    UserCreate:
      type: object
      properties:
        email:
          type: string
          format: email
        given_name:
          type: string
          maxLength: 256
        family_name:
          type: string
          maxLength: 256
        password:
          type: string
          writeOnly: true
          maxLength: 64
          minLength: 8
        repeated_password:
          type: string
          writeOnly: true
          maxLength: 64
          minLength: 8
      required:
      - email
      - family_name
      - given_name
      - password
      - repeated_password
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
